### PR TITLE
The override in extendClass wasn't defaulting to true

### PR DESCRIPTION
**Pull request by Xananax**
The examples given were not working until I added this line, or changed the last extend() call in Class to 
extend(Class,body,true)

### CODE REVIEW

**Comment by jiem** [comment]
Hi Xananax, could you tell me which example does not work? I checked the file `example/example.html` and it's working, that is, the `sayHello` method of class `Dreamer` overrides the `sayHello` method of super class `Person`.
But it's true that I haven't explained in details how method overriding works with `my.class`. It works as in Java classes: by default, 1/ child class methods overrides father class methods, 2/ methods from implemented classes don't override previous methods, 3/ child static methods don't override father static methods. 
As for the method `extendClass`, you're right, the `override` param is not defaulting to true but to `undefined` but it's working as so since the conditional to see whether methods should be overidden is `override === false`.

**Comment by Xananax** [comment]
I don't know. You're right, it is all working.
It must be something I did on my end.
I am using your library daily without any problem.

On a side note, github notifications are invisible. Took me six months to know I had one.

**Comment by Xananax** [comment]
On an unrelated note, but I don't know how to contact you, I have forked my-class and packaged it as an NPM module (just added package.json and pushed to npm repo, basically).
I added you as a contributor in package.json (package.json does not support multiple authors), gave attribution in the readme, and kept the MIT license.
Please tell me if this is ok.
The repo is found at https://github.com/yelo-npm/my-class

**Comment by jiem** [comment]
Hi Xanaxax, thanks for doing the NPM module, I'm of course OK, that's
great!! Best, Jie

PS: I'm having a pb w/ my dedicated server, I can't get the docs for myjs
for the moment

2012/12/13 Xananax notifications@github.com

**Pull request closed without merging**
